name: Generate Go package
run-name: Generate Go ${{ inputs.VERSION || '1.19.0' }}
on:
  workflow_dispatch:
    inputs:
      VERSION:
        description: 'Go version to build and upload'
        required: true
        default: '1.19.0'
      PUBLISH_RELEASES:
        description: 'Whether to publish releases'
        type: boolean
        required: true
        default: false
  pull_request:
    paths-ignore:
    - 'versions-manifest.json'
    - 'LICENSE'
    - '**.md'
    branches:
    - 'main'

jobs:
  go:
    name: Go
    uses: actions/versions-package-tools/.github/workflows/build-tool-packages.yml@main
    with:
      tool-name: "go"
      tool-version: ${{ inputs.VERSION || '1.19.0' }}
      publish-release: ${{ inputs.PUBLISH_RELEASES || false }}
    secrets: inherit
